name: Update App Version Number by Release

on:
  release:
    types: [published]

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update version in pubspec.yaml
        run: |
          VERSION=${{ github.event.release.tag_name }}
          VERSION=${VERSION#v}
          BUILD_NUMBER=${{ github.run_number }}
          NEW_VERSION="${VERSION}+${BUILD_NUMBER}"
          sed -i "s/^version:.*/version: ${NEW_VERSION}/" pubspec.yaml
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add pubspec.yaml
          git commit -m "Päivitetty versio: ${NEW_VERSION}" || echo "Ei muutoksia"
          git push
